export const API=process.env.NEXT_PUBLIC_API_URL??"http://localhost:8000";
export type AdminUser={id:string;name:string;email:string;role:string;permissions:string[];is_active:boolean;status:string;avatar:string|null;must_change_password:boolean;last_login_at:string|null;created_by:string|null;created_by_name?:string|null;updated_at:string|null;created_at:string};
export type Report={id:string;text:string;category_suggested:string;status:"pending"|"reviewed"|"rejected";created_at:string};
export type Dashboard={total_analyzed:number;analyses_today:number;analyses_this_month:number;category_counts:Record<string,number>;reports_total:number;reports_pending:number;reports_reviewed:number;candidates_total:number;education_published:number;recent_reports:Report[];model_status:string;privacy_mode:string;daily_stats:{day:string;count:number}[];source_counts:Record<string,number>;database_engine:string;database_connected:boolean};
export type Candidate={id:string;report_id:string|null;text_anonymized:string;category:string;source:string;data_type:"primer"|"sekunder"|"sintetis";validation_status:"pending"|"approved"|"rejected"|"verified";split:"train"|"validation"|"test"|null;validator:string|null;notes:string|null;is_duplicate:boolean;is_archived:boolean;nseae_validation:Record<string,boolean>;created_at:string;updated_at:string};
export type Role={id:string;name:string;slug:string;description:string|null;is_system:boolean;user_count:number;permissions:string[]};
export type Permission={id:string;name:string;slug:string;module:string;description:string|null};
export function authHeaders(json=false):HeadersInit{const token=localStorage.getItem("nusaguard_token")??"";return json?{"Content-Type":"application/json",Authorization:`Bearer ${token}`}:{Authorization:`Bearer ${token}`}}
export async function adminFetch<T>(path:string,init:RequestInit={}):Promise<T>{const response=await fetch(`${API}${path}`,{...init,headers:{...authHeaders(Boolean(init.body)),...init.headers}});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.detail??"Permintaan admin gagal.")}if(response.status===204)return undefined as T;return response.json()}
export async function adminLogout(){try{await adminFetch<void>("/api/auth/logout",{method:"POST"})}finally{localStorage.removeItem("nusaguard_token")}}
