"use client";
import Link from "next/link";
import {useRouter,useSearchParams} from "next/navigation";
import {ReactNode,useEffect,useMemo,useState} from "react";
import {adminFetch,adminLogout,AdminUser,API,Dashboard} from "./admin-api";
import {AdminProvider} from "./admin-context";
import styles from "./admin.module.css";
const nav=[["dashboard","⌂","Dashboard","dashboard.view"],["users","♙","Manajemen Pengguna","users.view"],["roles","⌘","Role & Permission","roles.manage"],["reports","◇","Laporan Modus","reports.view"],["candidates","▦","Kandidat Dataset","datasets.view"],["import","↑","Import Dataset","datasets.import"],["distribution","◫","Distribusi Dataset","datasets.view"],["nseae","N6","Validasi N-SEAE","nseae.validate"],["lexicons","Aa","Leksikon N-SEAE","lexicons.view"],["education","✦","Konten Edukasi","education.view"],["recommendations","✓","Rekomendasi Tindakan","recommendations.manage"],["categories","#6","Kategori Deteksi","statistics.view"],["statistics","▥","Statistik","statistics.view"],["model","AI","Monitoring Model","models.view"],["system","●","Status Sistem","models.view"],["roadmap","07","Roadmap","dashboard.view"],["activities","≡","Log Aktivitas","activity_logs.view"],["settings","⚙","Pengaturan","settings.manage"],["profile","●","Profil","profile.manage"]] as const;
export default function AdminShell({children}:{children:ReactNode}){
 const params=useSearchParams(),router=useRouter(),feature=params.get("fitur")??"dashboard";
 const[ready,setReady]=useState(false),[menuOpen,setMenuOpen]=useState(false),[collapsed,setCollapsed]=useState(false),[error,setError]=useState(""),[user,setUser]=useState<AdminUser>({id:"",name:"",email:"",role:"",permissions:[],is_active:false,status:"inactive",avatar:null,must_change_password:false,last_login_at:null,created_by:null,updated_at:null,created_at:""}),[status,setStatus]=useState<Dashboard|null>(null);
 useEffect(()=>{const timer=setTimeout(async()=>{const token=localStorage.getItem("nusaguard_token");if(!token){router.replace("/login");return}try{const response=await fetch(`${API}/api/auth/me`,{headers:{Authorization:`Bearer ${token}`}}),current=await response.json();if(!response.ok||!current.permissions.some((permission:string)=>nav.some(item=>item[3]===permission))){localStorage.removeItem("nusaguard_token");setError("Akun ini tidak memiliki hak panel admin.");return}setUser(current);setReady(true);void adminFetch<Dashboard>("/api/admin/dashboard").then(setStatus).catch(()=>setStatus(null))}catch{setError("Backend belum dapat dijangkau.")}},0);return()=>clearTimeout(timer)},[router]);
 const visible=useMemo(()=>nav.filter(([, , ,permission])=>user?.permissions.includes(permission)),[user]),current=nav.find(([id])=>id===feature)??nav[0];
 useEffect(()=>{if(ready&&!visible.some(([id])=>id===feature))router.replace("/admin")},[feature,ready,router,visible]);async function logout(){await adminLogout();router.replace("/login")}
 if(ready&&!user)return null;
 if(!ready)return <main className={styles.loginShell}><section className={styles.loginCard}><div className={styles.loginBrand}><span>NG</span><div><b>NusaGuard</b><small>AREA TERLINDUNGI</small></div></div><p className={styles.kicker}>OTORISASI BERBASIS ROLE</p><h1>{error?"Akses ditolak.":"Memverifikasi sesi…"}</h1><p>{error||"Hak akses akun sedang diperiksa oleh server."}</p>{error&&<Link href="/login">Kembali ke halaman login</Link>}</section><div className={styles.loginVisual}><span>PRIVACY-FIRST OPERATIONS</span><div className={styles.rings}><i/><i/><b>N</b></div><p>Role dan permission berasal dari database serta diverifikasi oleh backend.</p></div></main>;
 return <AdminProvider value={user}><div className={`${styles.shell} ${collapsed?styles.collapsed:""}`}><aside className={`${styles.sidebar} ${menuOpen?styles.open:""}`}><div className={styles.logo}><span>NG</span><div><b>NusaGuard</b><small>ADMIN CONSOLE</small></div></div><button className={styles.collapseButton} onClick={()=>setCollapsed(v=>!v)} aria-label={collapsed?"Perbesar sidebar":"Perkecil sidebar"}>{collapsed?"›":"‹"}</button><nav>{visible.map(([id,icon,label])=><Link title={label} key={id} href={id==="dashboard"?"/admin":`/admin?fitur=${id}`} className={feature===id?styles.active:""} onClick={()=>setMenuOpen(false)}><i>{icon}</i><span>{label}</span></Link>)}</nav><div className={styles.sideBottom}><div className={styles.privacyChip}>● PRIVASI AKTIF<small>Teks analisis tidak disimpan</small></div><Link href="/">↗ Situs publik</Link><button onClick={()=>void logout()}>Keluar</button></div></aside><main className={styles.main}><header><button className={styles.menu} onClick={()=>setMenuOpen(v=>!v)}>☰</button><div className={styles.headerTitle}><p>ADMIN / {current[2].toUpperCase()}</p><h1>{current[2]}</h1></div><div className={styles.headerRight}><span className={styles.live}>● {status?status.model_status.toUpperCase():"STATUS AI TIDAK TERSEDIA"}</span>{user.permissions.includes("reports.view")&&<Link href="/admin?fitur=reports" className={styles.notification} title={`${status?.reports_pending??0} laporan menunggu`}>◇ {status?.reports_pending??0}</Link>}<div className={styles.profileSummary}><span className={styles.avatar}>{user.name.slice(0,2).toUpperCase()}</span><div><b>{user.name}</b><small>{user.role.replaceAll("_"," ")}</small></div></div><button onClick={()=>void logout()} title="Keluar">↗</button></div></header><section className={styles.content}>{children}</section><footer><span>NusaGuard Admin Console</span><span>RBAC · audit aktif · analisis ephemeral</span></footer></main></div></AdminProvider>
}
