"use client";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import {adminFetch} from "./admin-api";import styles from "./admin.module.css";
type Item={id:string;title:string;content:string;category:string|null;risk_level:"LOW"|"MEDIUM"|"HIGH"|null;nseae_indicator:string|null;display_order:number;is_active:boolean};
const categories=["Aman","Phishing/Link Berbahaya","Social Engineering","Penipuan Investasi","Penipuan Rekrutmen","Penipuan Romansa"];
const empty:Omit<Item,"id">={title:"",content:"",category:null,risk_level:null,nseae_indicator:null,display_order:0,is_active:true};
export default function RecommendationsPage(){
 const[items,setItems]=useState<Item[]>([]),[risk,setRisk]=useState("all"),[open,setOpen]=useState(false),[editing,setEditing]=useState<Item|null>(null),[draft,setDraft]=useState(empty),[message,setMessage]=useState("");
 const load=useCallback(()=>adminFetch<Item[]>("/api/admin/recommendations").then(setItems).catch(e=>setMessage(e.message)),[]);useEffect(()=>{void load()},[load]);
 const rows=useMemo(()=>items.filter(item=>risk==="all"||item.risk_level===risk).sort((a,b)=>a.display_order-b.display_order),[items,risk]);
 function show(item?:Item){setEditing(item??null);setDraft(item??empty);setOpen(true)}
 async function save(e:FormEvent){e.preventDefault();try{await adminFetch(editing?`/api/admin/recommendations/${editing.id}`:"/api/admin/recommendations",{method:editing?"PATCH":"POST",body:JSON.stringify(draft)});setOpen(false);setMessage("Rekomendasi berhasil disimpan.");await load()}catch(x){setMessage(x instanceof Error?x.message:"Rekomendasi gagal disimpan.")}}
 async function archive(id:string){if(!confirm("Arsipkan rekomendasi ini?"))return;await adminFetch(`/api/admin/recommendations/${id}`,{method:"DELETE"});await load()}
 return <><div className={styles.sectionHead}><div><span>CONTEXTUAL GUIDANCE</span><h2>Rekomendasi tindakan</h2></div><button className={styles.createButton} onClick={()=>show()}>+ Tambah rekomendasi</button></div>{message&&<div className={message.includes("berhasil")?styles.success:styles.alert}>{message}</div>}<div className={styles.filters}>{["all","LOW","MEDIUM","HIGH"].map(item=><button key={item} className={risk===item?styles.selected:""} onClick={()=>setRisk(item)}>{item}</button>)}</div><div className={styles.cardGrid}>{rows.map(item=><article className={styles.panel} key={item.id}><div className={styles.panelHead}><div><span>{item.category??item.nseae_indicator??"UMUM"}</span><h3>{item.title}</h3></div><b>{item.risk_level??"SEMUA"}</b></div><p>{item.content}</p><div className={styles.userActions}><button onClick={()=>show(item)}>Edit</button><button onClick={()=>void archive(item.id)}>Arsipkan</button></div></article>)}</div>{!rows.length&&<div className={styles.empty}>Belum ada rekomendasi pada filter ini.</div>}{open&&<div className={styles.modalBackdrop}><section className={styles.modal}><button className={styles.modalClose} onClick={()=>setOpen(false)}>×</button><span>REKOMENDASI DINAMIS</span><h2>{editing?"Edit rekomendasi":"Tambah rekomendasi"}</h2><form onSubmit={save}><label>Judul<input required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Isi rekomendasi<textarea required minLength={10} value={draft.content} onChange={e=>setDraft({...draft,content:e.target.value})}/></label><label>Kategori<select value={draft.category??""} onChange={e=>setDraft({...draft,category:e.target.value||null})}><option value="">Semua kategori</option>{categories.map(item=><option key={item}>{item}</option>)}</select></label><label>Tingkat risiko<select value={draft.risk_level??""} onChange={e=>setDraft({...draft,risk_level:(e.target.value||null) as Item["risk_level"]})}><option value="">Semua risiko</option><option>LOW</option><option>MEDIUM</option><option>HIGH</option></select></label><label>Indikator terkait<input value={draft.nseae_indicator??""} onChange={e=>setDraft({...draft,nseae_indicator:e.target.value||null})}/></label><label>Urutan<input type="number" min="0" value={draft.display_order} onChange={e=>setDraft({...draft,display_order:Number(e.target.value)})}/></label><label><input type="checkbox" checked={draft.is_active} onChange={e=>setDraft({...draft,is_active:e.target.checked})}/> Aktif</label><div className={styles.modalActions}><button type="button" onClick={()=>setOpen(false)}>Batal</button><button>Simpan</button></div></form></section></div>}</>}
