"use client";

import { useState } from "react";
import type { AnalyzeResponse } from "./types";

const API = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";
const labels: Record<string,string> = { urgency:"Urgensi", authority:"Otoritas", fear:"Ketakutan", reward:"Imbalan", impersonation:"Penyamaran", credential_request:"Permintaan data" };

export default function Home() {
  const [message,setMessage]=useState(""); const [result,setResult]=useState<AnalyzeResponse|null>(null);
  const [loading,setLoading]=useState(false);
  const [error,setError]=useState<string|null>(null); const [large,setLarge]=useState(false); const [contrast,setContrast]=useState(false);
  async function analyze(){ if(!message.trim())return; setLoading(true);setError(null);setResult(null); try{const r=await fetch(`${API}/api/analyze`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:message,source:"manual_web"})});if(!r.ok)throw new Error();setResult(await r.json())}catch{setError("API belum dapat dijangkau. Periksa NEXT_PUBLIC_API_URL dan status backend.")}finally{setLoading(false)} }
  return <div className={`${large?"large":""} ${contrast?"contrast":""}`}>
    <header><a className="brand" href="#top"><span>NG</span>NusaGuard</a><nav><a href="#analisis">Analisis</a><a href="/statistics">Statistik</a><a href="/education">Edukasi modus</a><a href="/report">Lapor</a><a href="/dataset">Dataset</a><a href="/login">Masuk</a></nav><div className="access"><button onClick={()=>setLarge(v=>!v)} aria-pressed={large}>A+</button><button onClick={()=>setContrast(v=>!v)} aria-pressed={contrast}>◐</button></div></header>
    <main id="top">
      <section className="hero"><div><p className="eyebrow">AI ANTI-PENIPUAN BERBAHASA INDONESIA</p><h1>Berhenti sejenak.<br/><em>Periksa pesannya.</em></h1><p className="lead">NusaGuard membaca pola manipulasi dalam pesan mencurigakan dan memberi alasan yang bisa kamu pahami—sebelum kamu klik atau transfer.</p><a className="primary" href="#analisis">Periksa pesan sekarang →</a></div><div className="signal" aria-hidden><div className="orbit one"/><div className="orbit two"/><div className="shield">N</div><span className="ping p1"/><span className="ping p2"/></div></section>
      <section id="analisis" className="analyzer"><div className="section-title"><p className="eyebrow">PEMERIKSAAN EPHEMERAL</p><h2>Tempel pesan mencurigakan</h2><p>Isi pesan dikirim untuk dianalisis dan tidak disimpan sebagai histori.</p></div><div className="workspace"><div className="input-card"><label htmlFor="message">Isi pesan WhatsApp / SMS</label><textarea id="message" maxLength={5000} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Contoh: Selamat! Anda mendapat hadiah. Segera kirim OTP..."/><div className="input-meta"><span>{message.length}/5000</span><button className="primary" onClick={analyze} disabled={loading||!message.trim()}>{loading?"Menganalisis…":"Analisis pesan →"}</button></div>{error&&<p className="error" role="alert">{error}</p>}</div>
      <div className={`result-card ${result?result.risk_level.toLowerCase():"empty"}`}>{!result?<div className="empty-state"><div className="radar">⌁</div><h3>Hasil akan muncul di sini</h3><p>Enam indikator N-SEAE diperiksa secara transparan.</p></div>:<><div className="risk-head"><div><span className="badge">RISIKO {result.risk_level}</span><h3>{result.category}</h3><small>Mesin: {result.model_source} · confidence model {Math.round(result.model_confidence*100)}%{result.fusion_applied?" · dikoreksi fusion N-SEAE":""}</small></div><div className="score">{Math.round(result.risk_score*100)}<small>/100</small></div></div><p>{result.explanation}</p><div className="bars">{Object.entries(result.nseae_scores).map(([key,value])=><div key={key}><span>{labels[key]??key}</span><i><b style={{width:`${value*100}%`}}/></i><strong>{Math.round(value*100)}</strong></div>)}</div><div className="recommend"><b>Langkah aman</b><p>{result.recommendation}</p></div></>}</div></div></section>
      <section className="education"><div className="section-title"><p className="eyebrow">KONTRIBUSI & PENGETAHUAN</p><h2>Dari laporan, kembali melindungi publik.</h2></div><div className="category-grid"><article><span>01</span><h3>Edukasi dinamis</h3><p>Kenali modus yang diperbarui admin berdasarkan temuan terbaru.</p><a href="/education">Buka edukasi →</a></article><article><span>02</span><h3>Lapor penipuan</h3><p>Kirim contoh secara sukarela tanpa identitas pribadi.</p><a href="/report">Buat laporan →</a></article><article><span>03</span><h3>Dataset publik</h3><p>Akses laporan yang sudah ditinjau dan dianonimkan.</p><a href="/dataset">Lihat dataset →</a></article></div></section>
      <section id="privasi" className="privacy"><p className="eyebrow">PRIVASI SEJAK AWAL</p><h2>Pesanmu lewat, bukan menetap.</h2><div><p>Analisis berlangsung di memori. Teks tidak masuk histori, log, atau dataset otomatis.</p><p>Laporan modus baru hanya disimpan jika kamu memilih mengirim dan memberi persetujuan eksplisit.</p><p>NusaGuard tidak membaca database WhatsApp, kontak, nomor telepon, atau histori percakapan.</p></div></section>
    </main><footer><span>NusaGuard · Prototype kompetisi</span><span>IndoBERT + N-SEAE · FastAPI · Next.js · Android</span></footer>
  </div>;
}

